#!/bin/sh
#
# agent-schedule-install.sh {install|uninstall|status|kick} <agent>
#
# Manages the per-agent launchd job on this machine. The generated plist is
# deliberately barebones — calendar times + one command — and only ever calls
# scripts/agent-scheduled-run.sh <agent> in this checkout; every bit of logic
# lives in the repo. Times come from SCHEDULE in
# scripts/agent-schedules/<agent>.env. See docs/agent-automation-setup.md.
#
#   install    write ~/Library/LaunchAgents/com.nyc311.agent.<agent>.plist and
#              (re)load it — re-run after changing SCHEDULE
#   uninstall  unload and delete the plist
#   status     show launchd's view of the job
#   kick       start a run now (same path launchd takes), without waiting

set -eu

die() { printf 'agent-schedule-install: %s\n' "$*" >&2; exit 1; }

sub=${1:-}
agent=${2:-}
[ -n "$sub" ] && [ -n "$agent" ] || die "usage: agent-schedule-install.sh {install|uninstall|status|kick} <agent>"

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
config="$script_dir/agent-schedules/$agent.env"
[ -f "$config" ] || die "no schedule config at $config"

label="com.nyc311.agent.$agent"
plist="$HOME/Library/LaunchAgents/$label.plist"
domain="gui/$(id -u)"
log_dir="${AGENT_LOG_ROOT:-"$HOME/Library/Logs/nyc311-agents"}/$agent"

cmd_install() {
  # shellcheck disable=SC1090
  . "$config"
  : "${SCHEDULE:?SCHEDULE not set in $config}"

  intervals=""
  for t in $SCHEDULE; do
    case "$t" in
      [0-2][0-9]:[0-5][0-9]) : ;;
      *) die "bad SCHEDULE time '$t' (want HH:MM)" ;;
    esac
    h=${t%%:*}; m=${t#*:}
    h=${h#0}; m=${m#0}
    [ "$h" -le 23 ] || die "bad SCHEDULE hour in '$t'"
    intervals="$intervals
    <dict><key>Hour</key><integer>${h:-0}</integer><key>Minute</key><integer>${m:-0}</integer></dict>"
  done

  mkdir -p "$HOME/Library/LaunchAgents" "$log_dir"
  cat >"$plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by scripts/agent-schedule-install.sh — edit SCHEDULE in scripts/agent-schedules/$agent.env, not this file. -->
<plist version="1.0">
<dict>
  <key>Label</key><string>$label</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>$script_dir/agent-scheduled-run.sh</string>
    <string>$agent</string>
  </array>
  <key>StartCalendarInterval</key>
  <array>$intervals
  </array>
  <key>StandardOutPath</key><string>$log_dir/launchd.log</string>
  <key>StandardErrorPath</key><string>$log_dir/launchd.log</string>
</dict>
</plist>
EOF
  plutil -lint "$plist" >/dev/null || die "generated plist failed plutil -lint: $plist"

  launchctl bootout "$domain/$label" 2>/dev/null || true
  launchctl bootstrap "$domain" "$plist"
  printf 'installed %s — runs at %s (local time)\n' "$label" "$SCHEDULE"
}

cmd_uninstall() {
  launchctl bootout "$domain/$label" 2>/dev/null || true
  rm -f "$plist"
  printf 'uninstalled %s\n' "$label"
}

case "$sub" in
  install) cmd_install ;;
  uninstall) cmd_uninstall ;;
  status) launchctl print "$domain/$label" | grep -E 'state =|last exit code|runs =|path =' || die "$label not loaded" ;;
  kick) launchctl kickstart "$domain/$label" && printf 'started %s — tail -f %s/*.log\n' "$label" "$log_dir" ;;
  *) die "usage: agent-schedule-install.sh {install|uninstall|status|kick} <agent>" ;;
esac
